#!/usr/bin/env ruby
#
#   gunicorn_status - A munin plugin for Linux to monitor gunicorn processes
#  Copyright (C) 2011 Kristaps Kūlis - kristaps.kulis@gmail.com
#  Based on unicorn munin plugin by Shinji Furuya http://exchange.munin-monitoring.org/plugins/unicorn_status/details
#  Licensed under the MIT license:
#  http://www.opensource.org/licenses/mit-license.php
#


module Munin
  class GunicornStatus
    attr_reader :pid_file

    def initialize(pid)
      @pid_file = pid
    end

    def master_pid
      File.read(pid_file).to_i
    end

    def worker_pids
      result = []
      ps_output = `ps w --ppid #{master_pid}`
      ps_output.split("\n").each do |line|
        chunks = line.strip.split(/\s+/, 5)
        pid, pcmd = chunks[0], chunks[4]
        next if pid !~ /\A\d+\z/ or pcmd !~ /gunicorn/
          result << pid.to_i
      end
      result
    end

    def worker_count
      worker_pids.size
    end

    def idle_worker_count
      result = 0
      before_cpu = {}
      worker_pids.each do |pid|
        before_cpu[pid] = cpu_time(pid)
      end
      sleep 1
      after_cpu = {}
      worker_pids.each do |pid|
        after_cpu[pid] = cpu_time(pid)
      end
      worker_pids.each do |pid|
        result += 1 if after_cpu[pid] - before_cpu[pid] == 0
      end
      result
    end

    def cpu_time(pid)
      usr, sys = `cat /proc/#{pid}/stat | awk '{print $14,$15 }'`.strip.split(/\s+/).collect { |i| i.to_i }
      usr + sys
    end
  end
end

case ARGV[0]
when "autoconf"
  puts "yes"
when "config"
  puts "graph_title Gunicorn - Status"
  puts "graph_args -l 0"
  puts "graph_vlabel number of workers"
  puts "graph_category Gunicorn"
  puts "total_worker.label total_workers"
  puts "idle_worker.label idle_workers"
else
  m = Munin::GunicornStatus.new(ENV['GUNICORN_PIDFILE'])
  puts "total_worker.value #{m.worker_count}"
  puts "idle_worker.value #{m.idle_worker_count}"
end
